name = "ai-gateway"
main = "src/index.ts"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[placement]
mode = "targeted"
region = "aws:us-east-1"

# KV namespace — wrangler will auto-resolve by name
[[kv_namespaces]]
binding = "KV"

# Variables
[vars]
OPENAI_FALLBACK_BASE_URL = "https://gateway.ai.cloudflare.com/v1/2f7e6d8790e237dd47eafaeefb2af549/default/openai"
